services:
  - type: web
    name: skin-sattva-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py

databases:
  - name: skin-sattva-db
    plan: free
    databaseName: skin_sattva_db