"""Create bookings table

Revision ID: d7ebeb22d602
Revises: 
Create Date: 2026-03-23 15:47:16.994814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7ebeb22d602'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_checks')
    op.alter_column('bookings', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('bookings', 'patient_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('bookings', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('bookings', 'service',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('bookings', 'preferred_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('bookings', 'preferred_time',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('bookings', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=True,
               existing_server_default=sa.text("'Pending'::text"))
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'sheet_sync_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=True,
               existing_server_default=sa.text("'not_configured'::text"))
    op.create_index(op.f('ix_bookings_phone'), 'bookings', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_phone'), table_name='bookings')
    op.alter_column('bookings', 'sheet_sync_status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'not_configured'::text"))
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'Pending'::text"))
    op.alter_column('bookings', 'preferred_time',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('bookings', 'preferred_date',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('bookings', 'service',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('bookings', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('bookings', 'patient_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('bookings', 'id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('status_checks',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('client_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('status_checks_pkey'))
    )
    # ### end Alembic commands ###
